#!/bin/bash

# Set IP name
IPname=$(echo $1 | cut -d'-' -f 3)

echo "#########################################"
echo "## Run synthesis flow for $IPname"
echo "#########################################"

# Check if ${PROJECT_DIR} is empty
if [[ -z ${PROJECT_DIR} ]]; then
	echo "ERROR: You need to source setup_ENV at the root of the project folder"
	exit 1;
fi

# Check if IP was specify in the command
if [[ $# -ne 1 ]]; then
	echo "ERROR: Illegal number of parameters"
	echo "./run_synthesis --<IPname>"
	exit 1
fi

# Check if you are in the right folder
if [[ ! $PWD == "${PROJECT_DIR}/modules/${IPname}/asic/synth" ]]; then
	echo "ERROR: You need to be in the synthesis directory of your module (asic/synth/)"
	echo "Check if you have specify the correct IP name"
	exit 1
fi

# Check if the .synopsys_dc.setup exists
if [[ ! -e .synopsys_dc.setup ]]; then
	echo "ERROR: Missing .synopsys_dc.setup file"
	exit 1
fi


export RTL_FOLDER="${PROJECT_DIR}/modules/${IPname}/rtl/src/"


iter=0
synth_dir="synthesis"

while [[ -d "${synth_dir}_${iter}" ]]; do
	iter=$((iter+1))
done
synth_dir="${synth_dir}_${iter}"

mkdir ${synth_dir}
cp synth_attributes.do ${synth_dir}
cp .synopsys_dc.setup ${synth_dir}
cd ${synth_dir}

design_vision -f ../synth_flow.do -no_gui -output_log_file synthesis.log
