LIB = $(PROJECT_LIBS_DIR)/lib_CDR

SVSRCS := ${CDR_DIR}/rtl/src/bit_recovery.sv \
							${CDR_DIR}/rtl/src/cdr.sv \
							${CDR_DIR}/rtl/src/bit_recovery_CDR.sv

VHDLSRCS :=

VLOG_OPT += -incr -sv
VCOM_OPT +=

compile: lib
	@echo "**[MAKE] Compiling RTL sources."
	@vlog -work $(LIB) $(VLOG_OPT) $(SVSRCS)

lib:
	@echo "**[MAKE]** Creating library $(LIB)."
	@if [ -d $(LIB) ]; then \
		rm -rf $(LIB); \
		echo "--[MAKE] Removed old library $(LIB)."; \
	fi
	vlib $(LIB);

clean:
	@echo "**[MAKE] Cleaning simulation directory and library $(LIB)."
	@if [ -d $(LIB) ]; then rm -rf $(LIB); fi
