set init_layout_view ""
set init_abstract_name ""
set init_verilog "./INPUT_DATA/TL_codeur_IQ_io.v  ./INPUT_DATA/TL_codeur_IQ.v"
set init_mmmc_file "./view_definition.tcl"
set init_lef_file "/tp/xph2app/xph2app112/projet_Numerique/projet_zigbee/modules/codiq/asic/par/Innovus/INPUT_DATA /softslin/AMS_410_ISR15/cds/HK_C35/LEF/c35b4/CORELIB.lef /softslin/AMS_410_ISR15/cds/HK_C35/LEF/c35b4/IOLIB_4M.lef"
set init_top_cell "TL_codeur_IQ_io"
set init_gnd_net "gnd! gnd3r! gnd3o!"
set init_pwr_net "vdd! vdd3r1! vdd3r2! vdd3o!"
set cts_cell_list "CLKIN0 CLKIN1 CLKIN2 CLKIN3 CLKIN4 CLKIN6 CLKIN8 CLKIN10 CLKIN12 CLKIN15 CLKBU2 CLKBU4 CLKBU6 CLKBU8 CLKBU12 CLKBU15"
#ligne 5 edit par nycro
